server:
    port: 8443
    servlet:
        context-path: /springbootdemo
spring:
    datasource:
#        url: jdbc:mysql://173.2.58.212:3306/test?useSSL=false
        url: jdbc:mysql://192.168.31.17:3306/socks?useSSL=false
        username: root
        password: 123456
        host: 192.168.31.17
        port: 3306
        database: socks
        driver-class-name: com.mysql.jdbc.Driver
        test-while-idle: true
        test-on-borrow: true
        validation-query: select 1 from dual
        time-between-eviction-runs-millis: 30
        min-evictable-idle-time-millis: 30

